config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :kullanicis
  get 'home/index'
  root 'home#index'
  get 'home/sinavlar'
  get 'home/aciklama'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kullanici.rb
class Kullanici < ApplicationRecord

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



         has_many :kullanicis
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sinavlar
  end
end

app/controllers/kullanicis_controller.rb
class KullanicisController < ApplicationController
  before_action :set_kullanici, only: [:show, :edit, :update, :destroy]

  # GET /kullanicis
  # GET /kullanicis.json
  def index
    @kullanicis = Kullanici.all
  end

  # GET /kullanicis/1
  # GET /kullanicis/1.json
  def show
  end

  # GET /kullanicis/new
  def new
    @kullanici = Kullanici.new
  end

  # GET /kullanicis/1/edit
  def edit
  end

  # POST /kullanicis
  # POST /kullanicis.json
  def create
    @kullanici = Kullanici.new(kullanici_params)

    respond_to do |format|
      if @kullanici.save
        format.html { redirect_to @kullanici, notice: 'Kullanici was successfully created.' }
        format.json { render :show, status: :created, location: @kullanici }
      else
        format.html { render :new }
        format.json { render json: @kullanici.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kullanicis/1
  # PATCH/PUT /kullanicis/1.json
  def update
    respond_to do |format|
      if @kullanici.update(kullanici_params)
        format.html { redirect_to @kullanici, notice: 'Kullanici was successfully updated.' }
        format.json { render :show, status: :ok, location: @kullanici }
      else
        format.html { render :edit }
        format.json { render json: @kullanici.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kullanicis/1
  # DELETE /kullanicis/1.json
  def destroy
    @kullanici.destroy
    respond_to do |format|
      format.html { redirect_to kullanicis_url, notice: 'Kullanici was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kullanici
      @kullanici = Kullanici.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kullanici_params
      params.require(:kullanici).permit(:ad, :soyad, :email, :telefon_numarası, :okudugunuz_okul, :calıstıgınız_is_yeri, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kullanicis_helper.rb
module KullanicisHelper
end

app/views/home/_aramacubugu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Aktüerya Nedir?', root_path, class:"navbar-brand"  %>
<div class="container-fluid">
    <%= link_to "Amaç", home_aciklama_path, class:"navbar-brand" %>0


  <div class="container-fluid">
    <%= link_to "Aktüerlik Sınavları", home_sinavlar_path, class:"navbar-brand" %>
    
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      </br></br>
        <li class="nav-item">
          <%= link_to "Üyeler", kullanicis_path, class:"navbar-dark" %>
        </li>
    

        <div class="container-fluid"><div class="container-fluid">
       

    
   
   <% if user_signed_in? %>

     	<li class="nav-item">
         <%= link_to "Kayıt Ol", new_kullanici_path, class:"navbar-dark" %>
        </li>

        <li class="nav-item">
         <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
    
        <li class="nav-item">
         <%= link_to "Edit Profile", edit_user_registration_path, class:"navb-link" %>
           </li>
   <% else %>
      <div class="container-fluid"><div class="container-fluid">
        <li class="nav-item">
         <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
    
          <div class="container-fluid"><div class="container-fluid">
        <li class="nav-item">
         <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
    
    <% end %>

 
  
 </div>
 
    
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Aktüerya Nedir?', root_path, class:"navbar-brand"  %>
<div class="container-fluid">
    <%= link_to "Amaç", home_aciklama_path, class:"navbar-brand" %>0


  <div class="container-fluid">
    <%= link_to "Aktüerlik Sınavları", home_sinavlar_path, class:"navbar-brand" %>
    
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
      </br></br>
        <li class="container-fluid">
          <%= link_to "Üyeler", kullanicis_path, class:"navbar-brand" %>
        </li>
    

        <div class="container-fluid"><div class="container-fluid">
       

    
   
   <% if user_signed_in? %>

     	<li class="container-fluid">
         <%= link_to "Kayıt Ol", new_kullanici_path, class:"navbar-brand" %>
        </li>

        <li class="container-fluid">
         <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"navbar-brand" %>
        </li>
    
        <li class="container-fluid">
         <%= link_to "Edit Profile", edit_user_registration_path, class:"navbar-brand" %>
           </li>
   <% else %>
      <div class="container-fluid"><div class="container-fluid">
        <li class="nav-item">
         <%= link_to "Sign Up", new_user_registration_path, class:"navbar-brand" %>
        </li>
    
          <div class="container-fluid"><div class="container-fluid">
        <li class="nav-item">
         <%= link_to "Sign In", new_user_session_path, class:"navbar-brand" %>
        </li>
    
    <% end %>

 
  
 </div>
 
    
   
       </ul>
    
</nav>
       </ul>
    
</nav>

app/views/home/aciklama.html.erb
<div class="container"> 
 	</br></br>
 	<h4>Aktüerya mezunlarının birbirlerinden haberdar olması, istenirse iletişimin sağlanması amaçlanmıştır. </h4>

app/views/home/index.html.erb
 <div class="container"><div class="container">
  	</br></br>
  	<h1>Aktüerya Nedir?</h1>
  </br>
<p>Aktüerya bilimi insanların; doğum, ölüm, hastalık, sakatlık, emeklilik gibi yaşamını; yangın, kaza, deprem, sel, hırsızlık gibi mal varlığını etkileyen rastgeleliğe bağlı, öngörülemeyen olaylarla ve bu olayların finansal etkileriyle ilgilenir. Aktüerler, bu tür olayların oluşma riskini analiz etmek, olasılıklarını tahmin etmek ve bu olayların finansal etkilerini hafifletici güvenlik programlarını oluşturmak üzere eğitim alırlar.
</br></br>
Her insan ve kurum farklı riskler ile karşılaşabilir. Aktüerler, riski ölçümü ve risk yönetiminde uzman olduklarından, toplumun fiziksel ve ekonomik koşullarının iyileştirilmesine önemli derecede katkı sağlarlar. Aktüerlerin geliştirdiği risk programları dikkate alınmadığında, ekonomik anlamda istenilmeyen sonuçlar ile karşılaşılması olasıdır.
</br></br>
Aktüerya eğitiminin amacı aktüerya, istatistik, matematik, sigortacılık, bilgisayar uygulamaları, ekonomi, finans gibi bilgilerle donatılmış; sosyoloji, felsefe, psikoloji gibi sosyal bilim dersleriyle desteklenmiş; bu bilgileri ilgili olduğu her alanda kullanılabilecek çağdaş, yaratıcı ve sorunları rasyonel olarak çözebilecek aktüer adayları yetiştirmektir.
</br></br>
Dört yıllık Aktüerya Bilimleri Lisans Programında önce matematik, istatistik, bilgisayar ve ekonomi ağırlıklı temel dersler, daha sonra finansal matematik, aktüerya matematiği, risk kuramı, hayat ve hayat dışı sigortalar matematiği, emeklilik matematiği, hasar modelleri, aktüeryal yazılımlar, aktüerya uygulamaları gibi uzmanlık dersleri verilmektedir. Aktüerya eğitiminde başarılı olan öğrenciler gerekli kredileri tamamlayarak istatistik, işletme ya da iktisat gibi çeşitli alanlarda yan dal sertifikası da alabilirler.
</br></br>
Aktüer olmak isteyen adayların matematik, istatistik, finans bilgisi güçlü, bilgisayar programlarından da yararlanarak sayısal analizler yapmaktan hoşlanan, girişimci, araştırmacı, yeniliklere açık, ekonomi ve finans ile yakından ilgili kişiler olmaları gerekir.
</br></br>
Aktüerler, ekonominin tüm sektörlerinde çalışabilmekle beraber daha çok sigorta, brokerlık, eksperlik, danışmanlık şirketleri, ticari bankalar, yatırım bankaları, yatırım ,şirketleri gibi finansal hizmet sektörü ile Sosyal Güvenlik Kurumu, Hazine Müsteşarlığı gibi kamu kurumlarında da çalışabilmektedirler. Aktüerlerin ağırlıklı olarak sigorta sektöründe çalışmasının nedeni, toplumda risk yönetimine en çok ihtiyaç duyulan sektör olmasıdır. Finansal olarak kaybetme riski, belli bir prim karşılığında sigorta şirketine devredilir. Aktüerler, sigorta sektöründe sigorta ürünleri oluşturarak bu ürünlere ilişkin primlerin ve rezervlerin belirlenmesini ve bu primler karşılığında sigortalılara ödenecek hasar ödemelerinin yapılabilmesini sağlamak için şirketin aktüeryal dengesinin oluşturulmasında anahtar rol oynarlar.
</br></br>
Mezunlar, ulusal ya da uluslararası aktüerlik sınavlarına girerek Aktüerler Yönetmeliği'nin öngördüğü koşulları yerine getirdikleri takdirde, imza yetkisine sahip Aktüer unvanını da alabilirler. Aktüerlerin iş alanları; matematik, istatistik, ekonomi, bilgisayar yazılımları, finans, mevzuat, muhasebe ve sigortacılık konularında değişen dünya koşullarına uygun olarak kendilerini geliştirdikleri takdirde oldukça geniştir. Aktüerlik mesleği, ABD ve Avrupa'da ücret, prestij ve iş tatmini açısından en iyi on meslek sıralamasında ilk beşin içerisinde yer almaktadır.  
</br></br>
Aktüerliğin toplum tarafından yeni tanınan bir meslek olması nedeniyle Aktüerya eğitimi almanın, bir takım zorlukları olduğu gibi, aktüer sayısının azlığı, sektörün aktüerlere olan ihtiyacı ve dünyada aktüerliğin aranan meslek grupları içerisinde yer alması gibi avantajları da bulunmaktadır.
</br></br>
Aktüerya Bilimleri Bölümü misyonunu, edindiği bilgileri kullanabilecek çağdaş, yaratıcı ve sorunları bağımsız olarak çözebilecek, insanlığın sorunlarına duyarlı, birlikte çalışmayı ve düşünmeyi öğrenmiş aktüerya uzmanları yetiştirmek, ulusal ve uluslararası ortamlarda vereceği eğitim ve üreteceği bilgi ile ulusal ve evrensel kalkınmaya katkıda bulunan bir bölüm olmak; vizyonunu ise, araştırma, öğretim ve hizmet alanlarındaki üretimi ile evrensel değerler ışığında ülkenin geleceği için yetiştirdiği üstün nitelikli bireyleri topluma sunmak olarak belirlemiştir.</p>

app/views/home/sinavlar.html.erb
<div class="container"> 
 	</br></br>
 	<h1>Aktüerlik sınavları</h1>
 	
 </br>
1.AŞAMA
</br></br>
		-Matematik</br>
		-Finansal Matematik</br>
		-İstatistik ve Olasılık</br>
		-Temel Sigortacılık ve Ekonomi
	</br></br>
	2.AŞAMA
	</br></br>
		-Finans Teorisi ve Uygulamaları</br>
		-Sigorta Matematiği</br>
		-Muhasebe ve Finansal Raporlama</br>
		-Risk Analizi ve Aktüeryal Modelleme
</br></br>
	3.AŞAMA
</br></br>
	-Hayat Sigortaları</br>
	-Hayat Dışı Sigortalar</br>
	-Finans, Yatırım ve Risk Yönetimi</br>
	-Sağlık Sigortaları
	</p>

app/views/kullanicis/_form.html.erb
<%= form_with(model: kullanici) do |form| %>
  <% if kullanici.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kullanici.errors.count, "error") %> prohibited this kullanici from being saved:</h2>

      <ul>
        <% kullanici.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    
    <%= form.text_field :ad, class:"form-control", placeholder:"Ad" %>
  </div>

  <div class="field mb-3">
    
    <%= form.text_field :soyad, class:"form-control", placeholder:"Soyad"%>
  </div>

  <div class="field mb-3">
    <% form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field mb-3">
    
    <%= form.number_field :telefon_numarası,class:"form-control", placeholder:"Telefon Numarası" %>
  </div>

  <div class="field mb-3">
    
    <%= form.text_area :okudugunuz_okul, class:"form-control", placeholder:"Okudugunuz Okul" %>
  </div>

  <div class="field mb-3">
    
    <%= form.text_area :calıstıgınız_is_yeri, class:"form-control", placeholder:"Calıstıgınız Is  Yeri" %>

  </div>
   <div class="field mb-3">
    
    <%= form.number_field :user_id, id: :kullanici_user_id,
     class:"form-control", value:current_user.id, type: :hidden %>

  </div>




  <div class="actions">
    <%= form.submit class:'btn brn-secondary' %>
  </div>
<% end %>

app/views/kullanicis/edit.html.erb
<h1>Editing Kullanici</h1>
</br>
<%= render 'form', kullanici: @kullanici %>
</br>
<%= link_to 'Show', @kullanici, class:"btn btn-secondary" %> 
<%= link_to 'Back', kullanicis_path, class:"btn btn-dark" %>

app/views/kullanicis/index.html.erb
</br>
<h1>Kayıtlı Üyeler</h1>
</br>

<table class="table table-striped table-bordered">
  <thead class="table-info">
    <tr>
      <th>Ad</th>
      <th>Soyad</th>
      <th>Email</th>
      <th>Telefon numarası</th>
      <th>Okudugunuz okul</th>
      <th>Calıstıgınız is yeri</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kullanicis.each do |kullanici| %>
      <tr>
        <td><%= kullanici.ad %></td>
        <td><%= kullanici.soyad %></td>
        <td><%= kullanici.email %></td>
        <td><%= kullanici.telefon_numarası %></td>
        <td><%= kullanici.okudugunuz_okul %></td>
        <td><%= kullanici.calıstıgınız_is_yeri %></td>
        <td><%= link_to 'Show', kullanici %></td>
        <td><%= link_to 'Edit', edit_kullanici_path(kullanici) %></td>
        <td><%= link_to 'Destroy', kullanici, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Kayıt Ol', new_kullanici_path, class:"btn btn-secondary" %>

app/views/kullanicis/new.html.erb
</br>
<h1>Kayıt Ol</h1>
</br>
<div class="alert alert-warning" role="alert">
  Tüm Alanları Doldurunuz!
</div>
</br>

<%= render 'form', kullanici: @kullanici %>
</br>

<%= link_to 'Back', kullanicis_path, class:"btn btn-dark" %>

app/views/kullanicis/show.html.erb
<p>
  <strong>Ad:</strong>
  <%= @kullanici.ad %>
</p>

<p>
  <strong>Soyad:</strong>
  <%= @kullanici.soyad %>
</p>

<p>
  <strong>Email:</strong>
  <%= @kullanici.email %>
</p>

<p>
  <strong>Telefon numarası:</strong>
  <%= @kullanici.telefon_numarası %>
</p>

<p>
  <strong>Okudugunuz okul:</strong>
  <%= @kullanici.okudugunuz_okul %>
</p>

<p>
  <strong>Calıstıgınız is yeri:</strong>
  <%= @kullanici.calıstıgınız_is_yeri %>
</p>

<%= link_to 'Edit', edit_kullanici_path(@kullanici), class:"btn btn-secondary" %> |
<%= link_to 'Back', kullanicis_path, class:"btn btn-secondary" %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Aktuerya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

   <%= render 'home/aramacubugu' %>
   <div class="container">
    </br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>

  
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>